export const OPEN_POSITION_SLIPPAGE = 0.01
export const CLOSE_POSITION_SLIPPAGE = 0.9999
export const SWAP_OPEN_POSITION_SLIPPAGE = 0.01
export const SWAP_CLOSE_POSITION_SLIPPAGE = 0.9999
export const FORCE_SWAP_SLIPPAGE = 0.9999
export const GAS_SUI_SWAP_SLIPPAGE = 0.01