services:
  server:
    build:
      context: ../..
      dockerfile: apps/kani-inspector/Dockerfile
    env_file:
      - ../../.env.docker
    volumes:
      - ../../.mount:/usr/src/app/.mount

# docker build -t kanibot/kani-inspector:latest -f apps/kani-inspector/Dockerfile . && docker push kanibot/kani-inspector:latest
# docker compose -f apps/kani-inspector/compose.yaml up --build -d
