export enum EventName {
    ClmmLiquidityPoolsSynced = "clmm.liquidity.pools.synced",
    DlmmLiquidityPoolsSynced = "dlmm.liquidity.pools.synced",
    ReinitializeBalancers = "reinitialize.balancers",
    CoordinatorExecutorCreated = "coordinator.executor.created",
    CoordinatorExecutorDeleted = "coordinator.executor.deleted",
    CoordinatorExecutorUpdated = "coordinator.executor.updated",
    ExecutorBotUpdated = "executor.bot.updated",
    ExecutorBotCreated = "executor.bot.created",
    ExecutorBotDeleted = "executor.bot.deleted",
    ClmmPositionOpenRequested = "clmm.position.open.requested",
    ClmmPositionCloseRequested = "clmm.position.close.requested",
    DlmmPositionOpenRequested = "dlmm.position.open.requested",
    DlmmPositionCloseRequested = "dlmm.position.close.requested",
}