services:
  server:
    build:
      context: ../..
      dockerfile: apps/kani-interface/Dockerfile

# docker build -t kanibot/kani-interface:latest -f apps/kani-interface/Dockerfile . && docker push kanibot/kani-interface:latest

