services:
  server:
    build:
      context: ../..
      dockerfile: apps/kani-interface/Dockerfile
    env_file:
      - ../../.env.secret
    environment:
      NODE_ENV: production

#docker compose -f apps/kani-interface/compose.yaml up -d --build