import Decimal from "decimal.js"
const LOW_SLIPPAGE = new Decimal(0.9) //  10%
const HIGH_SLIPPAGE = new Decimal(0.9999) // 99.99%
export const OPEN_POSITION_SLIPPAGE = LOW_SLIPPAGE 
export const CLOSE_POSITION_SLIPPAGE = HIGH_SLIPPAGE 
export const SWAP_OPEN_POSITION_SLIPPAGE = LOW_SLIPPAGE 
export const SWAP_CLOSE_POSITION_SLIPPAGE = HIGH_SLIPPAGE 
export const FORCE_SWAP_SLIPPAGE = HIGH_SLIPPAGE
export const GAS_SUI_SWAP_SLIPPAGE = LOW_SLIPPAGE
export const FLEXIBLE_INPUT_SWAP_SLIPPAGE = LOW_SLIPPAGE