import {
    Injectable
} from "@nestjs/common"
import {
    InjectMemoryCache,
    InjectRedisCache
} from "./cache.decorators"
import {
    Cache
} from "cache-manager"
import {
    CacheKey,
    configMap
} from "./config"
import {
    CacheType,
    DelParams,
    GetParams, SetParams
} from "./types"
import {
    InjectSuperJson
} from "@modules/mixin"
import SuperJSON from "superjson"

@Injectable()
export class CacheService {
    constructor(
    // Redis-backed cache manager (shared across instances)
    @InjectRedisCache()
    private readonly redisCacheManager: Cache,

    // In-memory cache manager (per-instance, non-distributed)
    @InjectMemoryCache()
    private readonly memoryCacheManager: Cache,

    // SuperJSON is used to safely serialize / deserialize complex data types
    // (e.g. Dayjs, BigInt, Map, Set) when storing values in cache
    @InjectSuperJson()
    private readonly superjson: SuperJSON,
    ) {}
    
    /**
     * Get the cache key for a given cache key and arguments.
     * @param key - The cache key.
     * @param args - The arguments.
     * @returns The cache key.
     */
    getCacheKey(
        key: CacheKey,
        args?: Array<unknown>
    ): string {
        return `${key}:${args?.map(arg => typeof arg === "string" ? arg : JSON.stringify(arg)).join(":")}`
    }

    /**
   * Retrieve a cached value by logical cache key and optional arguments.
   *
   * Design notes:
   * - The physical cache key is generated by hashing:
   *   [cache key enum + optional arguments]
   * - `Redis` cache is shared across instances.
   * - `Memory` cache is local to the current process.
   *
   * @returns Parsed cache value, or `undefined` if the cache entry does not exist.
   */
    async get<K extends CacheKey>(
        {
            key,
            args,
            cacheType = CacheType.Redis,
        }: GetParams<K>
    ): Promise<typeof configMap[typeof key]["cacheResult"] | undefined> {
        const cacheKey = this.getCacheKey(
            key,
            args
        )
        const cacheManager =
      cacheType === CacheType.Redis
          ? this.redisCacheManager
          : this.memoryCacheManager

        const serializedCachedResult =
      await cacheManager.get<string>(cacheKey)

        if (!serializedCachedResult) {
            return undefined
        }
        // Deserialize using SuperJSON to restore complex types
        return this.superjson.parse<
      typeof configMap[typeof key]["cacheResult"]
    >(serializedCachedResult)
    }

    /**
   * Store a value in cache.
   *
   * Design notes:
   * - Cache values are serialized using SuperJSON.
   * - TTL is resolved from the cache configuration map by cache key.
   * - Redis TTL is in seconds.
   * - Memory cache TTL is converted to milliseconds.
   */
    async set<K extends keyof typeof configMap>(
        {
            key,
            args,
            cacheResult,
            cacheType = CacheType.Redis,
        }: SetParams<K>
    ): Promise<void> {
        const cacheKey = this.getCacheKey(
            key,
            args
        )
        const serializedCachedResult =
      this.superjson.stringify(cacheResult)

        const cacheManager =
      cacheType === CacheType.Redis
          ? this.redisCacheManager
          : this.memoryCacheManager

        const ttl =
      cacheType === CacheType.Redis
          ? configMap[key].ttl
          : configMap[key].ttl * 1000
        await cacheManager.set(
            cacheKey,
            serializedCachedResult,
            ttl,
        )
    }

    /**
   * Delete a cached value by logical cache key and arguments.
   *
   * - Uses the same hashed cache key as `get` and `set`.
   * - Cache deletion respects the selected cache type (Redis or Memory).
   */
    async del(
        {
            key,
            args,
            cacheType = CacheType.Redis,
        }: DelParams
    ): Promise<void> {
        const cacheKey = this.getCacheKey(
            key,
            args
        )
        const cacheManager =
      cacheType === CacheType.Redis
          ? this.redisCacheManager
          : this.memoryCacheManager

        await cacheManager.del(cacheKey)
    }
}
