name: build-and-push-kani-executor

on:
  push:
    branches: [main, build]
    paths:
      - "src/**"
      - "apps/kani-executor/**"
      - ".github/workflows/kani-executor.yaml"

env:
  IMAGE_NAME: kani-executor
  DOCKERFILE_PATH: apps/kani-executor/Dockerfile
  BUILD_CONTEXT: .
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: self-hosted
    environment: kani

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Docker login
        run: |
          echo "${DOCKER_PASSWORD}" | docker login \
            ${DOCKER_REGISTRY:-docker.io} \
            -u "${DOCKER_USERNAME}" \
            --password-stdin
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -f ${DOCKERFILE_PATH} \
            -t ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG} \
            ${BUILD_CONTEXT}
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push Docker image
        run: |
          docker push \
            ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}