name: build-and-push-kani-coordinator

on:
  push:
    branches: [main, build]
    paths:
      - "src/**"
      - "apps/kani-coordinator/**"
      - ".github/workflows/kani-coordinator.yaml"

env:
  IMAGE_NAME: kani-coordinator
  DOCKERFILE_PATH: apps/kani-coordinator/Dockerfile
  BUILD_CONTEXT: .
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: self-hosted
    environment: kani

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Docker login
        run: |
          echo "${DOCKER_PASSWORD}" | docker login \
            ${DOCKER_REGISTRY:-docker.io} \
            -u "${DOCKER_USERNAME}" \
            --password-stdin
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -f ${DOCKERFILE_PATH} \
            -t ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG} \
            ${BUILD_CONTEXT}
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push Docker image
        run: |
          docker push \
            ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Call Jenkins API to deploy the image
        run: |
          curl -X POST -H "Content-Type: application/json" -d '${{ secrets.JENKINS_URL }}/generic-webhook-trigger/invoke?token=${{ secrets.KANI_COORDINATOR_DEPLOYMENT_ROLLOUT_WEBHOOK_TOKEN }}'